// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5LDSfxUyscQzrnlGce3mkw9UU2-3eOIE',
    appId: '1:135517419909:android:e4b55917d995236e15acec',
    messagingSenderId: '135517419909',
    projectId: 'flutter-practice-125f6',
    authDomain: 'flutter-practice-125f6.firebaseapp.com',
    storageBucket: 'flutter-practice-125f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5LDSfxUyscQzrnlGce3mkw9UU2-3eOIE',
    appId: '1:135517419909:android:e4b55917d995236e15acec',
    messagingSenderId: '135517419909',
    projectId: 'flutter-practice-125f6',
    authDomain: 'flutter-practice-125f6.firebaseapp.com',
    storageBucket: 'flutter-practice-125f6.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyD5LDSfxUyscQzrnlGce3mkw9UU2-3eOIE',
  //   appId: '1:135517419909:android:e4b55917d995236e15acec',
  //   messagingSenderId: '135517419909',
  //   projectId: 'flutter-practice-125f6',
  //   authDomain: 'flutter-practice-125f6.firebaseapp.com',
  //   storageBucket: 'flutter-practice-125f6.firebasestorage.app',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'Add your API key here',
  //   appId: 'Add your App ID here',
  //   messagingSenderId: 'Add your Messaging Sender ID here',
  //   projectId: 'Add your Project ID here',
  //   storageBucket: 'Add your Storage Bucket here',
  //   iosClientId: 'Add your iOS Client ID here',
  //   iosBundleId: 'Add your iOS Bundle ID here',
  // );
}
